### ISSUE TITLE
Contribution Link

### ISSUE THREAD

**Issue by souravseal99** [hargup/covidsupport#15]
A link to this repo can be added to the site, for an easy access. 
So that people who are able to help, can find this.

**Comment by hargup** [comment]
@souravseal99 Good idea.
Want to take a shot at adding that link? 

You can add that line in this file https://github.com/hargup/covidsupport/blob/76cf8a39de51f127ac55ad5b3a80d7c74596d23e/web/src/components/subcomponents/Resources.js

It can say "We can do so much more with your help, checkout out [our source code and contribution guide](https://github.com/hargup/covidsupport)."

**Comment by souravseal99** [comment]
> @souravseal99 Good idea.
> Want to take a shot at adding that link? 
> 
> You can add that line in this file https://github.com/hargup/covidsupport/blob/76cf8a39de51f127ac55ad5b3a80d7c74596d23e/web/src/components/subcomponents/Resources.js
> 
> It can say "We can do so much more with your help, checkout out [our source code and contribution guide](https://github.com/hargup/covidsupport)." 

Sure...

**Comment by hargup** [comment]
Closed with #16
